language: python
python: "3.7"
os: linux
dist: bionic
git:
  depth: 1
  quiet: true

jobs:
  include:
    - stage: Test
      name: "Test machine-learning - Machine-Learning: Python"
      before_install:
        - cd ../Machine-Learning/
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade pytest
      script: pytest